### ISSUE TITLE
Timeout on Ubuntu (GitHub Actions)

### ISSUE THREAD

**Issue by andreaswilli** [peterdanis/electron-puppeteer-demo#171]
Hi, thanks for the awesome template. It helped me setting up tests for my [electron app](https://github.com/andreaswilli/meta-grabber/tree/develop).

I want to run them using GitHub Actions on Windows, macOS and Ubuntu.
On Windows and macOS it works perfectly. Output from macOS:
```
> meta-grabber@0.2.0 test /Users/runner/work/meta-grabber/meta-grabber
> jest

PASS tests/app.test.js (5.738 s)
  Home
    ✓ show initial instructions in snackbar (383 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        5.802 s
Ran all test suites.
```
However, on Ubuntu the tests time out:
```
> meta-grabber@0.2.0 test /home/runner/work/meta-grabber/meta-grabber
> jest

FAIL tests/app.test.js (21.057 s)
  Home
    ✕ show initial instructions in snackbar (1 ms)

  ● Home › show initial instructions in snackbar

    thrown: "Exceeded timeout of 20000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       9 | jest.setTimeout(timeout)
      10 |
    > 11 | beforeAll(async () => {
         | ^
      12 |   page = await electronTest.createPage()
      13 | })
      14 |

      at Object.<anonymous> (tests/app.test.js:11:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        21.109 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meta-grabber@0.2.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meta-grabber@0.2.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-16T13_14_15_279Z-debug.log
Error: Process completed with exit code 1.
```

This happens even with a long timeout like 60 seconds. I don't have an Ubuntu installation handy but I ran the tests on Pop!_OS which worked without an issue.

Do you maybe know what the issue could be?

**Comment by peterdanis** [comment]
Hi, usually linux containers on CI/CD platforms do not have X server running. On Github Action's `ubuntu-latest`  image you have to install a few dependencies and use `xvfb` to start these puppeteer tests correctly. Please see .. https://github.com/peterdanis/electron-puppeteer-demo/blob/31b5e3ea75f9ceabfe4786020df55beb2b2d8897/.github/workflows/tests.yml#L51 .. and linux specific lines above it.

If you are already doing that I am sorry I currently don't actively work with Electron and can't help much on that topic.

**Comment by andreaswilli** [comment]
Thanks, it works 🚀

I needed to replace `npm run test` with `xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' npm run test` for the ubuntu environment. Installing additional dependencies does not seem to be necessary.

**Comment by peterdanis** [comment]
> Thanks, it works 🚀
> 
> I needed to replace `npm run test` with `xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' npm run test` for the ubuntu environment. Installing additional dependencies does not seem to be necessary.

Glad it worked and thank you for feedback!
